version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    restart: always
    volumes:
      - ./v2ray-config.json:/etc/v2ray/config.json
    ports:
      - "10086:10086"
    # command: ["v2ray","-config=https://xxx.com"]

  v2scar:
    container_name: v2scar
    image: zionladder/v2scar
    restart: always
    depends_on:
      - v2ray
    links:
      - v2ray
    environment:
      XSCAR_SYNC_TIME: 60
      XSCAR_API_ENDPOINT: ""
      XSCAR_GRPC_ENDPOINT: "v2ray:8080"